### PR TITLE
added tf version to colab master notebook

### LINKED ISSUE #30: ImportError: cannot import name 'keras_export'
I am trying to run [this](https://colab.research.google.com/github/shaoanlu/fewshot-face-translation-GAN/blob/master/colab_demo.ipynb) notebook, but I am getting below error at this line `from models import FaceTranslationGANInferenceModel`

```
Using TensorFlow backend.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-13-e0f766e65a9c> in <module>()
----> 1 from models import FaceTranslationGANInferenceModel

13 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/initializers/initializers_v1.py in <module>()
     21 from tensorflow.python.framework import dtypes
     22 from tensorflow.python.ops import init_ops
---> 23 from tensorflow.python.util.tf_export import keras_export
     24 
     25 keras_export(v1=['keras.initializers.Zeros', 'keras.initializers.zeros'])(

ImportError: cannot import name 'keras_export'
```

Libraries: `tensorflow-gpu==1.13.1`, `keras==2.2.4`

### PR DESCRIPTION
**Pull request by amrzv**
Hi.
Added tf version 1.13.1 (from requirements), that needed to be installed, now notebook works well.
Founded some issues, that will be resolved: #30, #26, #35

### CODE REVIEW

**Comment by amrzv** [comment]
Update: should be `intel-tensorflow<2` works fine. See this issue: #7

**Comment by amrzv** [comment]
Now made it actually works with latest `tensorflow==2.5`. Allso, changes were made to submodule [face_toolbox_keras](https://github.com/shaoanlu/face_toolbox_keras/tree/fb472da7d6138845930bb86ca1993f5aaac6d78e)
Beside of rewriting code in new tensorflow style, there were some bugs like this one:
https://github.com/shaoanlu/fewshot-face-translation-GAN/blob/994a709494b77a1adf05b616a356ef0a2bc1567a/networks/generator.py#L27
 wrong mask shape:
```diff
- inp_segm_mask = Input(shape=(input_size, input_size, nc_in))
+ inp_segm_mask = Input(shape=(input_size*16, input_size*16, nc_in))
```

To run notebook you should open notebook from my fork [Open In Colab](https://colab.research.google.com/github/amrzv/fewshot-face-translation-GAN/blob/tf-version-in-notebook/colab_demo.ipynb) and change first line:
`!git clone --recursive https://github.com/shaoanlu/fewshot-face-translation-GAN.git`
to
`!git clone --recursive --branch tf-version-in-notebook https://github.com/amrzv/fewshot-face-translation-GAN.git`

Runs without errors in default colab environment without needed installations anything.

**Comment by daniellivingston** [comment]
Great work!

**Comment by Kritz23** [comment]
@amrzv  Amazing, I was trying by myself to get it resolved and found this after a day spent on errors. 
Cheers!

**Review by AbdelmoumenDeghbouche — APPROVED** [review]
